### ISSUE TITLE
Incorrect number of mobile searches

### ISSUE THREAD

**Issue by Brenex** [spatel4140/bing-rewards#1]
it is showing 100 more searches than I have left. See the following two images:

![screen shot 2018-01-11 at 3 04 01 pm](https://user-images.githubusercontent.com/3178983/34844860-d7631756-f6e0-11e7-834d-0a8355aa82e1.png)

![screen shot 2018-01-11 at 3 05 44 pm](https://user-images.githubusercontent.com/3178983/34844874-ee192c92-f6e0-11e7-86eb-9548213754e8.png)

**Comment by spatel4140** [comment]
Hey Brenex, 

I received an email from Microsoft Rewards about a week ago saying this month only (January 2018), you can earn 2x the mobile search points through the Microsoft Edge app for iOS and Android.

If you actually download the app and view your dashboard on there, you will see _"X of 200 points"_ if you are a Level 2 member. 

I've attempted to try earning these extra points using Microsoft Edge's user-agent for Android. The success rate has not been so consistent as you can probably see so there's still some experimenting I have to do with that. 

I hope you'll still enjoy earning the other points in the meantime! :) 

And just to make sure, you've pulled the most recent changes correct? I've commit a few times this week with small bug fixes here and there and want to ensure you have the latest one.

**Comment by Brenex** [comment]
I have the most recent commits. I redownloaded it now just in case but it seems to have worked this morning. I confirmed on my mobile phone that my account today is at 200 of 200.

**Comment by spatel4140** [comment]
Thanks for confirming. I'll leave this issue open until I can ensure it keeps working.

**Comment by Brenex** [comment]
Getting this with the newest
[output.txt](https://github.com/spatel4140/bing-rewards/files/1628448/output.txt)
 commit:

**Comment by Brenex** [comment]
Getting this with the newest commit:

![output](https://user-images.githubusercontent.com/3178983/34907227-3de8ebd6-f849-11e7-89b5-4ad24320352e.PNG)

**Comment by Brenex** [comment]
Yea, just a quick update that it is no longer finding or performing the extra 100 at all. Strange

**Comment by spatel4140** [comment]
Because Microsoft doesn't have an API for it, the way I retrieve the current search progress relies on the UI. If they were to change the way they display this information, the search would fail to complete. 

I've changed the code to rely slightly less on the exactness of the page elements.

**Comment by Brenex** [comment]
It has been working consistently for me for the past week or so. I think this can be closed now. Thanks for your hard work
