### ISSUE TITLE
can u pl add points status .

### ISSUE THREAD

**Issue by rrosajp** [spatel4140/bing-rewards#10]
can u pl check
`    def __get_current_points(self,driver):
        try:
            driver.get('https://account.microsoft.com/rewards/?ref=bingflyout&refd=www.bing.com')
            time.sleep(random.uniform(25, 34))
            #for element in points_elem:
            element = driver.find_elements_by_id('$ctrl.id')
            print('Total :  ',element[0].text)
            #print('life time total ',element[1].text)
            #print('day streck ',element[2].text)
            print('Days until next bonus :  ',element[3].text)
            print('Current status :  ',element[4].text)
            driver.switch_to.window(driver.window_handles[-1])
        except Exception as e:
            print('error:  %s' % format(e))
            return`
i m learning this stuff but it seems working with my script can u add to this one

<script src="https://gist.github.com/rrosajp/f83e30b00ceb6e7fb28bd209aba3bdf8.js"></script>

**Comment by rrosajp** [comment]
it give this error:
File "D:\GitHub\z_xbmc\br bots\comparing\bing-rewards-spatel4140\BingRewards\src\driver.py", line 652, in __complete_offers
    Driver.close(driver)
TypeError: unbound method close() must be called with Driver instance as first argument (got NoneType instance instead)

**Comment by spatel4140** [comment]
Nice code by the way, I incorporated it in the most recent commit. 

Can you print the entire error. It looks like there must have been multiple exceptions and this was only a piece of it. It may have occurred because the driver wasn't properly initialized but I am not able to reproduce the error.

**Comment by rrosajp** [comment]
here is full log by the way issue is in py 2.7  i try in py 3 and it work so u were right ,

Enter 	w for web, 
	m for mobile, 
	b for both, 
	o for offers, 
	a for all, 
	r for remaining (default) 
Input: 	o

	You selected offers

> Starting offers
Traceback (most recent call last):
  File "\bing-rewards-spatel4140\BingRewards\BingRewards.py", line 219, in <module>
    __main(args[0], arg1)
  File "\bing-rewards-spatel4140\BingRewards\BingRewards.py", line 154, in __main
    rewards.complete_offers()
  File "\bing-rewards-spatel4140\BingRewards\src\driver.py", line 688, in complete_offers
    driver = self.__complete_offers()
  File "\bing-rewards-spatel4140\BingRewards\src\driver.py", line 651, in __complete_offers
    Driver.close(driver)
TypeError: unbound method close() must be called with Driver instance as first argument (got NoneType instance instead)

**Comment by spatel4140** [comment]
Glad to hear it's working! 

Python 3 is one of the requirements although it's strange that the driver doesn't initialize properly with Python 2.
