### ISSUE TITLE
u may like to add this improvment .

### ISSUE THREAD

**Issue by rrosajp** [spatel4140/bing-rewards#13]
search term from google Trends.py to search .
 have added this on my local
`   
 def get_search_text(self):
        import src.googleTrends as gt
        gen = gt.queryGenerator(1)
        querylist = (gen.generateQueries(30, set()))
        return querylist
`

and in def _search()

`   
 def __search(self, driver, device):
        self.__sys_out(u"Starting search", 2)
        driver.get(self.__BING_URL)    

        prev_progress = -1
        try_count = 0
        qlist = self.get_search_text()
        while True:
            current_progress, complete_progress = self.__get_search_progress(driver, device)
            if complete_progress > 0:
                self.__sys_out_progress(current_progress, complete_progress, 3)
            if current_progress == complete_progress:
                break
            elif current_progress == prev_progress:
                try_count += 1
                if try_count == 4:
                    self.__sys_out(u"Failed to complete search", 2, True, True)
                    return False
            else:
                prev_progress = current_progress
                try_count = 0
        
            search_box = driver.find_element_by_id(u"sb_form_q")
            search_box.clear()
            query = str(qlist.pop()).replace(" ","+")
            
            search_box.send_keys(unicode(query), Keys.RETURN) # unique search term
            time.sleep(self.__rend_wait) # sleep for a few seconds

        self.__sys_out(u"Successfully completed search", 2, True, True)
        return True
`

and googleTrend.py  from [https://github.com/sealemar/BingRewards](url)

**Comment by spatel4140** [comment]
That looks great!

However, I've already begun putting something similar together using an API I uncovered. Check it out in the latest commit!

**Comment by rrosajp** [comment]
thanks it's work great.
