### ISSUE TITLE
Feature - Combine Projects

### ISSUE THREAD

**Issue by ShoGinn** [spatel4140/bing-rewards#14]
So your vision far surpasses mine and I find myself only keeping my repo up to add the selenium grid compatibility.

Not sure how familiar you are with selenium grid, but it allows an easy version of selenium to be ran and you can do multiple instances.

https://github.com/SeleniumHQ/selenium/wiki/Grid2

I run the docker version of it

https://github.com/SeleniumHQ/docker-selenium

My changes are very minimal.

I essentially added a new item to the rewards call

```
rewards = Rewards(os.path.join(DRIVERS_DIR, DRIVER), 
config.credentials["email"], 
config.credentials["password"], 
DEBUG, 
HEADLESS, 
GRID, 
config.credentials["hub"])
```

`GRID = True` is above like Headless and debug

I also added a new credential adding the selenium hub ip in the config so it can easily be called changed however you want to make it work (in docker its easy since its all dns linked).

Then under driver I had to define them as well.

```
def __init__(self, path, device, headless, grid, hub):
        self.driver = self.__get_driver(path, device, headless, grid, hub)
```

Then some specific items for the grid

```
 def get_driver(path, device, headless, grid, hub):
        if not grid:
            system = platform.system()
            if system == "Windows":
                if not path.endswith(".exe"):
                    path += ".exe"
            if not os.path.exists(path):
                Driver.__download_driver(path, system)

        options = webdriver.ChromeOptions()
        options.add_argument("--disable-extensions")
        options.add_argument('--start-maximized')
        options.add_argument("--log-level=3")
        options.add_experimental_option("prefs", {
            "profile.default_content_setting_values.geolocation": 1})  # geolocation permission, 0=Ask, 1=Allow, 2=Deny
        if headless:
            options.add_argument("--headless")

        if device == Driver.WEB_DEVICE:
            options.add_argument("user-agent=" + Driver.__WEB_USER_AGENT)
        else:
            options.add_argument("user-agent=" + Driver.__MOBILE_USER_AGENT)
        if grid:
            options.add_argument('--disable-infobars')
            options.add_argument('--incognito')
            caps = options.to_capabilities()
            driver = webdriver.Remote(command_executor='http://' + hub + ':4444/wd/hub', desired_capabilities=caps)
        if not grid:
            driver = webdriver.Chrome(path, chrome_options=options)
        # if not headless:
        #    driver.set_window_position(-2000, 0)
        return driver
```

And wherever the driver is called grid goes~

```
driver = Driver.get_driver(self.path, Driver.WEB_DEVICE, self.headless, self.grid, self.hub)
```

How hard would it be to make this work in your script?

I end up just forcing the code since I use the grid, but an option would be awesome ;)

My project for ref:
https://github.com/ShoGinn/bing-rewards

**Comment by spatel4140** [comment]
I am open to the idea, let me do some research :)

**Comment by ShoGinn** [comment]
Thanks!

Purely lazy on my end, I think it adds an awesome feature though (docker helps with version control)

**Comment by ShoGinn** [comment]
I took the time and merged yours with the grid.

Problem is, I have a hardcoded variable (GRID = TRUE) and your config file will fail unless you recreate it with a hub ip.

Maybe you can make the setup.py have "if hub then" 

My skills aren't that good

**Comment by spatel4140** [comment]
I haven't had time to play around with it but I'm thinking the docker container would make porting this to Mac or Linux way easier.. 

I think it may be possible to leave GRID = True and have the setup.py file set the hub IP to the local IP address. This would have the hub and node both run on the users machine. 

However, it seems a little overwhelming to take on at the moment so it may be a while until I get to it :(

**Comment by ShoGinn** [comment]
for sure!

Thats why I merged your new changes, because I was excited to try them out :)
