### ISSUE TITLE
Quiz stopped working

### ISSUE THREAD

**Issue by ShoGinn** [spatel4140/bing-rewards#15]
Not sure why, nothing is erring out, just indicates that the quizzes are complete but they are never clicked.

**Comment by spatel4140** [comment]
Looks like you can no longer simply click anywhere on an offer. Fixed in the new commit

**Comment by ShoGinn** [comment]
Quizes are saying they are complete but on one of my 2 accounts it is not actually complete.

**Comment by ShoGinn** [comment]
Seems to be functioning again maybe just a fluke!

-- I'll let you close this.

**Comment by spatel4140** [comment]
Hmm that sounds interesting, did the dashboard mark it as complete? And how much progress was made with the quiz?

**Comment by ShoGinn** [comment]
The dashboard did not mark it as complete.. but the script said it was complete. Not sure the total progress (if I remember it was none)
