### ISSUE TITLE
Mobile Searches Failing

### ISSUE THREAD

**Issue by ShoGinn** [spatel4140/bing-rewards#17]
I am having an issue with the mobile searches not registering.

It searches "NHL" "Nationals" "Hockey" and then checks the points 3 times then fails out.

Not sure how the new search works :)

**Comment by ShoGinn** [comment]
I looked more into the code, the search.log isn't being referenced, it just searches the same thing fresh.

Not sure if it should use the search.log as a reference point

**Comment by ShoGinn** [comment]
I know you are using trends, rather than pull %Y%m%d can you do a random past date in last 30 days?

Not sure how to code that.

That way you can at least give yourself a random selection

**Comment by ShoGinn** [comment]
If you look at the rewards.src at line 50

I added" 

```
        trending_date -= timedelta(days=random.uniform(1,30))
```

works perfect now ;)

**Comment by spatel4140** [comment]
You're absolutely right about search.log not being referenced. Great catch! 

I was accidently clearing the log if the script was rerun on the same day and only reading it in if it was a new day. I had it flipped.

**Comment by ShoGinn** [comment]
Not sure how the bing algorithm is when it comes to search patterns, but having a randomizer of the trending seems prudent.

**Comment by spatel4140** [comment]
I can definitely add that :)

**Comment by ShoGinn** [comment]
Awesome looks good!
