### ISSUE TITLE
Doesn't Log In Anymore

### ISSUE THREAD

**Issue by Brenex** [spatel4140/bing-rewards#6]
Newest version, doesn't get passed logging in anymore. I noticed this a few days ago. I am on the newest dashboard too.

![screen shot 2018-03-25 at 11 31 05 pm](https://user-images.githubusercontent.com/3178983/37885678-a2697cc4-3084-11e8-874a-1ee333db001b.png)

**Comment by spatel4140** [comment]
Can you try deleting the contents of BingRewards/drivers/ and running again. Seems to resolved with the latest chromedriver.

**Comment by Brenex** [comment]
Seems to be fine after deleting the driver. Thanks!
