### ISSUE TITLE
Weekly Quiz

### ISSUE THREAD

**Issue by ShoGinn** [spatel4140/bing-rewards#7]
Just wanted to see if you are working on those Friday quizzes..
I haven't been able to fully investigate the code yet and integrate it.
I only noticed it because the streak was never longer than 6 days.
Basically the script thinks it is good to go because it "clicks" on the item, but it never finishes.
All you need to do to complete the quiz is click through all the questions, wrong or right.

**Comment by spatel4140** [comment]
I've written the code for it but unfortunately haven't had the chance to test it. 

Do you know that they occur every Friday? Just so I can look out for it next time to see if successfully completes.

**Comment by spatel4140** [comment]
I've pushed the early code although I was able to get the points without completing the quiz oddly.

**Comment by ShoGinn** [comment]
Sorry was away from tech for a couple days. 
I thought it was everyday.

**Comment by spatel4140** [comment]
It appeared again this Friday and successfully completed on my end. The answers don't need to be correct like you stated. 

Are you still experiencing issues with the weekly quizzes?

**Comment by ShoGinn** [comment]
Weekly Quizzes are working! Thanks for the work.
