### ISSUE TITLE
Alerts?

### ISSUE THREAD

**Issue by ShoGinn** [spatel4140/bing-rewards#9]
The script had an error because of those "location" alerts that are thrown sometimes by bing.

I have been scouring the documentation for selenium and can't seem to find a good way to do the chrome web driver capabilities and the normal desired capabilities...

Curious if 
```"locationContextEnabled"```

is the solution..

**Comment by spatel4140** [comment]
Great idea!

I can confirm the following line successfully presets the permission where 2 is Deny, 1 is Allow and 0 is Ask every time:
options.add_experimental_option("prefs", {"profile.default_content_setting_values.geolocation" : 2})

I have not tested it on Bing itself but don't see why it wouldn't work as long as it's not set to 0.

**Comment by ShoGinn** [comment]
Seems to be working! I'll close this for now.
